### ISSUE TITLE
运行出现错误

### ISSUE THREAD

**Issue by shidianxia** [wd/simple-v2ray-gfwlist#1]
你好，我在树莓派上尝试使用，但是出现了很多报错。我对python完全不熟，能帮忙看怎么解决吗？谢谢！
错误信息：
```
pi@raspberrypi:~ $ ./svgfw -d
2019-09-27 14:49:50,038 Utils: DEBUG [main/1050] version 0.3 run on Linux/4.19.66-v7+/armv7l
2019-09-27 14:49:50,040 GFW: DEBUG [__init__/787] init
2019-09-27 14:49:50,051 GFW: DEBUG [_ini_to_python/803] Load ini file
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 981, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 831, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 568, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 329, in getMessage
    msg = str(self.msg)
  File "./svgfw", line 435, in __repr__
    progs = copy.deepcopy(self.progs)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
TypeError: cannot serialize '_io.TextIOWrapper' object
Call stack:
  File "./svgfw", line 1078, in <module>
    main()
  File "./svgfw", line 1052, in main
    gfw = GFW()
  File "./svgfw", line 796, in __init__
    self.init(config)
  File "./svgfw", line 883, in init
    self.logger.debug(self.config)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
```

**Comment by wd** [comment]
看着好像是配置文件错误
没有捕捉到具体错误。你是打算如何使用？可以贴一下配置看看，注意把密码服务器这些自己打码。

**Comment by wd** [comment]
对了 你的python 版本是多少？

**Comment by shidianxia** [comment]
多谢，这是我的配置文件：
```
# 下面所有的多行配置项，注意后面的行需要前面有空格
[main]
lists_dir = ./lists
run_dir = ./run

gfwlist = https://raw.github.com/gfwlist/gfwlist/master/gfwlist.txt

# 这里的 ip 不会走下面任何的规则
ip_blacklists_src =
ip_blacklists_dst =

# 可以增加需要加入到 SVGFW 规则的 iptables rules，会加到最前面，手动加入这个链的规则会被定时程序清空
iptables_rules = [["-p", "tcp", "--dport", "1234", "-j", "DNAT", "--to-destination", "1.1.1.1:53"]]

# 国外 dns
international_dns = 8.8.8.8
# 国内 dns
domestic_dns = 114.114.114.114

# dnsmasq 会把列表转发到这个端口查国外 dns
international_dns_local_port = 5353
dnsmasq_port = 53

# 可以使用 v2ray，ss，rely 三种中的一种
# 这三个配置一个就可以，如果配置了多项，会随机选一个
[ss]
# 针对每个 list 需要有一个 config，至少需要有 gfwlist_config
gfwlist_config = {
    "server":"193.110.201.225",
    "server_port":80,
    "local_address":"0.0.0.0",
    "local_port":1080,
    "password":"sdxnowall",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "fast_open":true,
    "plugin":"obfs-local",
    "plugin_opts":"obfs=http;obfs-host=101.132.138.0;failover=127.0.0.1:8080;fast-open"
 }

netflix_config = {
    "server":"103.214.44.172",
    "server_port":80,
    "local_address":"0.0.0.0",
    "local_port":1081,
    "password":"sdxnowall",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "fast_open":true,
    "plugin":"obfs-local",
    "plugin_opts":"obfs=http;obfs-host=101.132.138.0;failover=127.0.0.1:8080;fast-open"
 }

#[v2ray]
# 可以添加多余的 inbound
#inbounds = [
#   ]

# outbounds 必须是可用的，并且针对下面每个 list 都需要有对应的 outbound
#outbounds = [
#   ]

#[rely]
# 路由器内存小，也可以通过其他机器上面启动的服务来上网，比如树莓派或者 NAS
#ip = 

[dnsmasq]
ext_config = log-async = 20
       domain-needed
       no-negcache
       no-resolv
       #log-queries

[list_gfwlist]
# url =
socks_local_port = 1080

[list_netflix]
# 需要在 list_dir 里面有对应的文件
socks_local_port = 1081
```

> Python 3.5.3

**Comment by shidianxia** [comment]
多谢，这是我的配置文件：
```
# 下面所有的多行配置项，注意后面的行需要前面有空格
[main]
lists_dir = ./lists
run_dir = ./run

gfwlist = https://raw.github.com/gfwlist/gfwlist/master/gfwlist.txt

# 这里的 ip 不会走下面任何的规则
ip_blacklists_src =
ip_blacklists_dst =

# 可以增加需要加入到 SVGFW 规则的 iptables rules，会加到最前面，手动加入这个链的规则会被定时程序清空
iptables_rules = [["-p", "tcp", "--dport", "1234", "-j", "DNAT", "--to-destination", "1.1.1.1:53"]]

# 国外 dns
international_dns = 8.8.8.8
# 国内 dns
domestic_dns = 114.114.114.114

# dnsmasq 会把列表转发到这个端口查国外 dns
international_dns_local_port = 5353
dnsmasq_port = 53

# 可以使用 v2ray，ss，rely 三种中的一种
# 这三个配置一个就可以，如果配置了多项，会随机选一个
[ss]
# 针对每个 list 需要有一个 config，至少需要有 gfwlist_config
gfwlist_config = {
    "server":"",
    "server_port":80,
    "local_address":"0.0.0.0",
    "local_port":1080,
    "password":"",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "fast_open":true,
    "plugin":"obfs-local",
    "plugin_opts":"obfs=http;obfs-host=101.132.138.0;failover=127.0.0.1:8080;fast-open"
 }

netflix_config = {
    "server":"",
    "server_port":80,
    "local_address":"0.0.0.0",
    "local_port":1081,
    "password":"",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "fast_open":true,
    "plugin":"obfs-local",
    "plugin_opts":"obfs=http;obfs-host=101.132.138.0;failover=127.0.0.1:8080;fast-open"
 }

#[v2ray]
# 可以添加多余的 inbound
#inbounds = [
#   ]

# outbounds 必须是可用的，并且针对下面每个 list 都需要有对应的 outbound
#outbounds = [
#   ]

#[rely]
# 路由器内存小，也可以通过其他机器上面启动的服务来上网，比如树莓派或者 NAS
#ip = 

[dnsmasq]
ext_config = log-async = 20
       domain-needed
       no-negcache
       no-resolv
       #log-queries

[list_gfwlist]
# url =
socks_local_port = 1080

[list_netflix]
# 需要在 list_dir 里面有对应的文件
socks_local_port = 1081
```

> Python 3.5.3

**Comment by wd** [comment]
我手头没有电脑没法测试，没看出来问题，可能是 python 版本导致的，方便升级下 python 么？要不就等我10.1假期之后看了...

**Comment by shidianxia** [comment]
我试试看升级python，你用的版本是多少？

**Comment by wd** [comment]
我用的 3.7 的

**Comment by shidianxia** [comment]
3.7 的可以正常运行了，但是好像没有效果，我查看 `sudo iptables -L -n`，输出的规则都是空的：
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```
似乎是 iptables的规则没有生效，也没有报错...

**Comment by shidianxia** [comment]
升级到 3.7 以后运行成功了，但是 iptables 规则似乎没有生效，也没有报错。

**Comment by wd** [comment]
需要查 nat 表 你可以执行下 status 看看输出。
也可以直接 dig 查查 twitter 域名的 ip 返回2个ip就是对的

**Comment by shidianxia** [comment]
谢谢！查询 nat 表后发现正常。最后一步步排查，发现 ss-tunnel 虽然运行了，但是无法代理 dns，非常不稳定，最后用了 dnscrypt-proxy 代替了 ss-tunnel，能够正常使用了。

**Comment by wd** [comment]
不错不错 你是第一个用户 🥰

我开始用的 v2ray 然后路由器上发现内存不太够 然后加了ss 发现被gfw干扰的厉害 后面打算再把 relay
搞好了加一个树莓派跑一下看看怎么样...

**Comment by shidianxia** [comment]
谢谢你的脚本，很好用。
很多路由器内存不够，cpu也不支持硬解，效果很不理想，所以我就用了树莓派，目前 SS 用 simple-obfs 的 http 模式非常稳定，80端口从来没干扰或者 QoS。但是 ss-tunnel 无法正常使用我也很纳闷，还好有别的 dns 方案，还算好解决。

我对 Python 不太熟悉，不过如果能支持到 3.5 版本的话，那 Debian 9/Ubuntu 18.04 的用户也可以直接使用了，毕竟编译安装最新版的 Python 在一些路由器上会很费时间。（我是把树莓派升级到 Debian 10 然后 apt 安装的 3.7 版本😂）

**Comment by wd** [comment]
ss-tunnel 解析 dns 是需要你的 ss 支持 udp relay 你可以看看是不是这样。

**Comment by shidianxia** [comment]
应该是这个原因了。
